export const HaNoiDistrict: Array<string> = [
  "Quan Hoang Mai",
  "Quan Long Bien",
  "Quan Thanh Xuan",
  "Quan Bac Tu Liem",
  "Quan Ba Dinh",
  "Quan Cau Giay",
  "Quan Dong Da",
  "Quan Hai Ba Trung",
  "Quan Hoan Kiem",
  "Quan Ha Dong",
  "Quan Tay Ho",
  "Quan Nam Tu Liem",
  "Huyen Gia Lam",
  "Huyen Quoc Oai",
  "Huyen Phu Xuyen",
  "Huyen Ba Vi",
  "Huyen My Duc",
  "Huyen Me Linh",
  "Huyen Soc Son",
  "Huyen Thach That",
];
