export const HoChiMinhDistrict: Array<string> = [
  "Quan 1",
  "Quan 3",
  "Quan 4",
  "Quan 5",
  "Quan 6",
  "Quan 7",
  "Quan 8",
  "Quan 10",
  "Quan 11",
  "Quan 12",
  "Quan Binh Thanh",
  "Quan Binh Tan",
  "Quan Go Vap",
  "Quan Phu Nhuan",
  "Quan Tan Binh",
  "Quan Tan Phu",
];
